'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '../../lib/api';import {AuthGate} from '../../components/AuthGate';
import {UserRound,RefreshCw,Check,ChevronDown,ExternalLink,Clock3,Search} from 'lucide-react';

function CounsellorDashboard(){
  const [queue,setQueue]=useState([]),[people,setPeople]=useState([]),[followups,setFollowups]=useState([]),[profiles,setProfiles]=useState({}),[q,setQ]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setBusy(true);try{const [h,b,f]=await Promise.all([api('/api/v1/handoff/queue'),api('/api/v1/beneficiaries'+(q?'?q='+encodeURIComponent(q):'')),api('/api/v1/followups')]);setQueue(h);setPeople(b);setFollowups(f);setErr('')}catch(e){setErr(`Backend unavailable: ${e.message}`)}finally{setBusy(false)}},[q]);
  useEffect(()=>{load()},[load]);
  async function showProfile(id){if(profiles[id])return;setProfiles(p=>({...p,[id]:{loading:true}}));try{const [profile,caseData]=await Promise.all([api(`/api/v1/staff/profile/${id}`),api(`/api/v1/staff/case/${id}`).catch(()=>null)]);setProfiles(p=>({...p,[id]:{...profile,case:caseData?.case||null}}))}catch(e){setProfiles(p=>({...p,[id]:{error:e.message}}))}}
  async function setHandoff(id,status){try{await api(`/api/v1/handoff/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setErr(e.message)}}
  async function setFollow(id,status){try{await api(`/api/v1/followups/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setErr(e.message)}}
  async function setOutcome(id,outcome){try{const d=await api(`/api/v1/case/${id}/outcome`,{method:'PATCH',body:JSON.stringify({outcome,note:''})});setProfiles(p=>({...p,[id]:{...p[id],case:d.case}}));await load()}catch(e){setErr(e.message)}}
  return <main className="shell"><div className="container"><div className="pagehead"><div className="eyebrow" style={{color:'#168f91'}}>COUNSELLOR WORKSPACE · DEMO ACCESS</div><h1>Support people, not just profiles.</h1><p>Review consented cases, accept handoffs, update outcomes and complete follow-up tasks.</p></div><div className="row wrap" style={{justifyContent:'space-between',marginBottom:16}}><span className="demo-badge">SIMULATED PILOT DATA · NOT A LIVE SERVICE</span><button className="button outline small" onClick={load} disabled={busy}><RefreshCw size={15}/>Refresh</button></div>{err&&<div className="notice" role="alert">{err}</div>}<div className="appgrid"><aside className="sidebar"><a className="sideitem active" href="#handoffs"><UserRound size={17}/><span>Handoff queue</span></a><a className="sideitem" href="#beneficiaries"><Search size={17}/><span>Beneficiary cases</span></a><a className="sideitem" href="#followups"><Clock3 size={17}/><span>Follow-ups</span></a></aside><div className="content">
  <section className="panel" id="handoffs"><div className="panel-head"><div><h2>Human handoff queue</h2><small className="muted">Automatically created when a pathway is selected.</small></div><span className="status amber">{queue.length} TOTAL</span></div>{queue.length===0?<div className="empty">No counsellor tasks yet. Complete an interview and select a pathway.</div>:<div className="tablewrap"><table><thead><tr><th>Request</th><th>Language</th><th>District</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{queue.map(h=><tr key={h.id}><td><b>{h.reason}</b><br/><small>{h.session_id.slice(0,9)}…</small></td><td>{h.language}</td><td>{h.district}</td><td>{h.priority}</td><td><span className="status">{h.status}</span></td><td><div className="row"><button className="button soft small" onClick={()=>setHandoff(h.id,'accepted')}>Accept</button><button className="button outline small" onClick={()=>setHandoff(h.id,'resolved')}>Resolve</button></div></td></tr>)}</tbody></table></div>}</section>
  <section className="panel" id="beneficiaries"><div className="panel-head"><div><h2>Consented cases</h2><small className="muted">Pseudonymous session IDs; limit 100.</small></div><div className="row"><input className="input" style={{maxWidth:210}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search district or ID"/><button className="button outline small" onClick={load}><Search size={15}/></button></div></div>{people.length===0?<div className="empty">No consented profiles yet.</div>:<div className="stack">{people.map(p=><details key={p.id} className="rec-card" onToggle={e=>e.currentTarget.open&&showProfile(p.id)}><summary style={{cursor:'pointer',listStyle:'none'}}><div className="row wrap" style={{justifyContent:'space-between'}}><div><span className="status teal">{p.language.toUpperCase()} · {p.state}</span><h3 style={{margin:'8px 0 3px',fontSize:15}}>{p.id.slice(0,12)}… · {p.district}</h3><small className="muted">Interest: {p.interest||'not shared'}</small></div><ChevronDown size={17}/></div></summary><div className="divider"/>{profiles[p.id]?.loading?<small>Loading case…</small>:profiles[p.id]?.error?<small>{profiles[p.id].error}</small>:<><div className="fieldgrid">{Object.entries(profiles[p.id]||{}).filter(([k])=>!['id','session_id','consent_status','case'].includes(k)).map(([k,v])=><div className="profileitem" key={k}><small>{k.replaceAll('_',' ')}</small><div>{Array.isArray(v)?v.join(', '):String(v||'Not shared')}</div></div>)}</div>{profiles[p.id]?.case&&<div className="notice blue" style={{marginTop:12}}>Case status: <b>{profiles[p.id].case.status}</b> · selected pathway: {profiles[p.id].case.selected_pathway_id||'none'} · outcome: {profiles[p.id].case.outcome}</div>}<div className="row wrap" style={{marginTop:12}}><Link href={`/beneficiary?session=${p.id}`} className="button soft small">Open beneficiary case <ExternalLink size={14}/></Link>{profiles[p.id]?.case&&<><button className="button outline small" onClick={()=>setOutcome(p.id,'training')}>Training started</button><button className="button outline small" onClick={()=>setOutcome(p.id,'employed')}>Employed</button><button className="button outline small" onClick={()=>setOutcome(p.id,'self_employed')}>Self-employed</button><button className="button outline small" onClick={()=>setOutcome(p.id,'not_proceeding')}>Not proceeding</button></>}</div></>}</details>)}</div>}</section>
  <section className="panel" id="followups"><div className="panel-head"><h2>Follow-up tasks</h2><span className="status">{followups.filter(x=>x.status==='pending').length} PENDING</span></div>{followups.length===0?<div className="empty">No follow-up tasks yet.</div>:<div className="tablewrap"><table><thead><tr><th>Session</th><th>Stage</th><th>Due</th><th>Note</th><th>Status</th><th/></tr></thead><tbody>{followups.map(f=><tr key={f.id}><td>{f.session_id.slice(0,10)}…</td><td>{f.stage}</td><td>{f.due_date||'—'}</td><td>{f.note}</td><td>{f.status}</td><td>{f.status==='pending'&&<button className="button soft small" onClick={()=>setFollow(f.id,'complete')}><Check size={13}/>Complete</button>}</td></tr>)}</tbody></table></div>}</section>
  </div></div><div className="notice blue" style={{marginBottom:30}}>Counsellor mode has demonstration access and is not protected by production authentication. Do not enter real personal information.</div></div></main>
}

export default function Counsellor(){return <AuthGate role="counsellor"><CounsellorDashboard/></AuthGate>}
